// Code generated by "stringer -type=Classification"; DO NOT EDIT.

package rules

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Private-0]
	_ = x[Public-1]
	_ = x[Confidential-2]
}

const _Classification_name = "PrivatePublicConfidential"

var _Classification_index = [...]uint8{0, 7, 13, 25}

func (i Classification) String() string {
	if i >= Classification(len(_Classification_index)-1) {
		return "Classification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Classification_name[_Classification_index[i]:_Classification_index[i+1]]
}
