// Code generated by "stringer -type=Status"; DO NOT EDIT.

package rules

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Tentative-0]
	_ = x[Confirmed-1]
	_ = x[Cancelled-2]
	_ = x[NeedsAction-3]
	_ = x[Completed-4]
	_ = x[InProcess-5]
	_ = x[Draft-6]
	_ = x[Final-7]
}

const _Status_name = "TentativeConfirmedCancelledNeedsActionCompletedInProcessDraftFinal"

var _Status_index = [...]uint8{0, 9, 18, 27, 38, 47, 56, 61, 66}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
