// Code generated by "stringer -type=TextCondition"; DO NOT EDIT.

package rules

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Contains-0]
	_ = x[NotContains-1]
	_ = x[Exact-2]
	_ = x[NotExact-3]
}

const _TextCondition_name = "ContainsNotContainsExactNotExact"

var _TextCondition_index = [...]uint8{0, 8, 19, 24, 32}

func (i TextCondition) String() string {
	if i >= TextCondition(len(_TextCondition_index)-1) {
		return "TextCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextCondition_name[_TextCondition_index[i]:_TextCondition_index[i+1]]
}
