// Code generated by "stringer -type=Transparency"; DO NOT EDIT.

package rules

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Transp-0]
	_ = x[Opaque-1]
	_ = x[Transparent-0]
}

const _Transparency_name = "TranspOpaque"

var _Transparency_index = [...]uint8{0, 6, 12}

func (i Transparency) String() string {
	if i >= Transparency(len(_Transparency_index)-1) {
		return "Transparency(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Transparency_name[_Transparency_index[i]:_Transparency_index[i+1]]
}
