version: 2

# Verifiable build
gomod:
  # Proxy a module from proxy.golang.org, making the builds verifiable.
  # This will only be effective if running against a tag. Snapshots will ignore
  # this setting.
  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
  proxy: true

  # If proxy is true, use these environment variables when running `go mod`
  # commands (namely, `go mod tidy`).
  #
  # Default: `os.Environ()` merged with what you set the root `env` section.
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

  # Sets the `-mod` flag value.
  mod: mod

  # Directory in which the go.mod file is.
  #
  # Default: ''.
  dir: .

# Reproducible build
builds:
  - id: build
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    main: ./cmd/icsFilter
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

# Exract SBOM
sboms:
  - artifacts: archive
  - id: source
    artifacts: source

checksum:
  name_template: "CHECKSUMS"

# Releasers
nfpms:
  - vendor: Ajabep
    homepage: https://github.com/ajabep/icsFilter
    maintainer: Ajabep <https://github.com/ajabep>
    description: |-
      Quick and dirty iCal (.ics) filter.
    license: UNLICENSE
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

    bindir: /usr/bin

    version_metadata: git

dockers:
  - ids:
      - build
    image_templates:
      - "gcr.io/ajabep/icsfilter:latest"
      - "gcr.io/ajabep/icsfilter:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

# Signing!
signs:
  - id: checksumSig
    cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum

docker_signs:
  - id: dockerSign
    cmd: cosign
    args:
      - "sign"
      - "--key=cosign.key"
      - "--upload=false"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: all
    ids:
      - dockers
